name: dreamflow
description: "A DreamFlow project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.0
  flutter_animate: ^4.0.0
  responsive_framework: ^1.0.0
  cupertino_icons: ^1.0.0
  video_player: ^2.8.2
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: 2.3.2
  path_provider: 2.1.4
  provider: 6.1.2
  http: '>=1.0.0'
  uuid: '>=3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/cars.png
    - assets/landing-page.mp4
    - assets/computer-vission.mp4
    - assets/computer-vission.jpg
    - assets/computer-vission3.png
    - assets/NLP.mp4
    - assets/nlp-.png
    - assets/nlp3.png
    - assets/3d-ann.png
    - assets/3d-ann1.png
    - assets/3d-ann2.png
    - assets/3d-ann3.png
    - assets/3d-ann4.png
    - assets/app-dev.mp4
    - assets/app-devv-.png
    - assets/find.png
    - assets/findrosi.png
    - assets/ai-consulting.mp4
    - assets/data-aquistion.mp4
    - assets/data-aquisition.png
    - assets/aiagent.mp4
    - assets/company-logo.png
    
